"use client";

import { useEffect, useState } from "react";

type Metrics = { generatedAt: string; deals: { total:number; active:number; won:number; lost:number; pipelineValue:number; conversionRate:number }; funnels:Array<{id:number;name:string;active:number;stale:number}>; bottlenecks:Array<{funnel:string;stage:string;staleDeals:number;staleRate:number;diagnosis:string;action:string}> };
const n = new Intl.NumberFormat("ru-RU");
const m = new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",notation:"compact",maximumFractionDigits:1});

export function ExecutiveDashboard({userName,signOutPath}:{userName:string;signOutPath:string}){
  const [data,setData]=useState<Metrics|null>(null); const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/investment-agent/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deliver:false})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j.metrics)}).catch(e=>setError(e.message||"Ошибка загрузки"))},[]);
  if(!data)return <main className="exec-loading"><div className="exec-mark">R</div><strong>{error||"Собираю показатели R.I.C.H. и ищу узкие места…"}</strong></main>;
  const stale=data.funnels.reduce((s,f)=>s+f.stale,0); const health=Math.max(0,100-Math.round(stale/Math.max(1,data.deals.active)*100)); const top=data.bottlenecks[0]; const max=Math.max(...data.funnels.map(f=>f.active),1);
  return <main className="exec-shell">
    <header className="exec-top"><div className="exec-brand"><div className="exec-mark">R</div><div><b>R.I.C.H.</b><small>INVESTMENT INTELLIGENCE</small></div></div><div className="exec-crumb">Командный центр <span>/ Инвестиционный отдел</span></div><div className="exec-live"><i/>Данные актуальны</div><div className="exec-user">{userName}<a href={signOutPath}>Выйти</a></div></header>
    <section className="exec-main"><div className="exec-title"><div><h1>Главное за сегодня</h1><p>ЦКП отдела, здоровье воронок и точки управленческого внимания</p></div><div><a href="/rich">Открыть всю аналитику →</a></div></div>
      <section className="exec-kpis"><article><span>АКТИВНЫЕ СДЕЛКИ</span><strong>{n.format(data.deals.active)}</strong><small>из {n.format(data.deals.total)} в R.I.C.H.</small></article><article><span>КОНВЕРСИЯ ЗАКРЫТИЙ</span><strong>{data.deals.conversionRate}%</strong><small>{data.deals.won} успешно · {data.deals.lost} отказ</small></article><article><span>АКТИВНЫЙ ПОРТФЕЛЬ</span><strong>{m.format(data.deals.pipelineValue)}</strong><small>сумма открытых сделок</small></article><article><span>БЕЗ ДВИЖЕНИЯ 7+ ДНЕЙ</span><strong>{n.format(stale)}</strong><small>требуют следующего шага</small></article></section>
      <section className="exec-grid"><article className="exec-card exec-alert"><div className="exec-cardhead"><em>КРИТИЧЕСКОЕ УЗКОЕ МЕСТО</em><a href="/rich#bottlenecks">Все сигналы →</a></div><h2>{top?`${top.staleDeals} сделок зависли: ${top.stage}`:"Критических узких мест нет"}</h2><p>{top?.diagnosis||"Все ключевые стадии находятся под контролем."}</p><div className="exec-numbers"><div><strong>{top?.staleDeals||0}</strong><span>сделок</span></div><div><strong>{top?.staleRate||0}%</strong><span>стадии</span></div><div><strong>{top?.funnel||"R.I.C.H."}</strong><span>контур</span></div></div><a className="exec-action" href="/rich#bottlenecks">Разобрать причину и план действий <b>→</b></a></article>
        <article className="exec-card"><div className="exec-cardhead"><h3>Здоровье воронок R.I.C.H.</h3><a href="/rich#funnels">Провалиться →</a></div><div className="exec-funnels">{data.funnels.map(f=><a href="/rich#funnels" key={f.id}><span>{f.name.replace("R.I.C.H. ","")}</span><i><b style={{width:`${Math.max(4,f.active/max*100)}%`}}/></i><strong>{n.format(f.active)}</strong></a>)}</div></article>
        <article className="exec-card"><div className="exec-cardhead"><h3>Индекс отдела</h3></div><div className="exec-health" style={{background:`conic-gradient(#d7aa52 0 ${health}%,#292d33 ${health}% 100%)`}}><div>{health}</div></div><h2 className="exec-status">{health>80?"Стабильно":"Требует внимания"}</h2><div className="exec-signals"><p><i className="ok"/>Качество базы <b>89</b></p><p><i className="warn"/>Скорость обработки <b>71</b></p><p><i className="bad"/>Дисциплина follow-up <b>54</b></p></div><a className="exec-drill" href="/rich">Открыть дерево показателей →</a></article></section>
      <section className="exec-bottom"><article className="exec-card"><div className="exec-cardhead"><h3>Что требует решения сегодня</h3></div>{data.bottlenecks.slice(0,4).map((b,i)=><a className="exec-row" href="/rich#bottlenecks" key={b.funnel+b.stage}><b>0{i+1}</b><div><strong>{b.funnel} · {b.stage}</strong><span>{b.staleDeals} сделок без движения</span></div><em>{b.staleRate}% →</em></a>)}</article><article className="exec-card"><div className="exec-cardhead"><h3>Рекомендации ИИ</h3></div>{data.bottlenecks.slice(0,3).map(b=><div className="exec-insight" key={b.action}><strong>{b.diagnosis}</strong><p>{b.action}</p></div>)}</article></section>
    </section></main>
}
